---
# task steps container images
images:
  bash: registry.access.redhat.com/ubi8-minimal:8.9
  skopeo: registry.access.redhat.com/ubi8/skopeo:8.9
  buildah: registry.access.redhat.com/ubi8/buildah:8.9
  s2i: registry.access.redhat.com/source-to-image/source-to-image-rhel8:v1.3.9-6
  
# source-to-image builder images, each language represents a distinct ecosystem the builder supports,
# sometimes it includes a specific version
s2iBuilders:
  python: image-registry.openshift-image-registry.svc:5000/openshift/python
  ruby: image-registry.openshift-image-registry.svc:5000/openshift/ruby
  perl: image-registry.openshift-image-registry.svc:5000/openshift/perl
  go: image-registry.openshift-image-registry.svc:5000/openshift/golang
  nodejs: image-registry.openshift-image-registry.svc:5000/openshift/nodejs
  php: image-registry.openshift-image-registry.svc:5000/openshift/php
  dotnet: image-registry.openshift-image-registry.svc:5000/openshift/dotnet
  java: image-registry.openshift-image-registry.svc:5000/openshift/java

annotations:
  tekton.dev/pipelines.minVersion: "0.41.0"
  tekton.dev/categories: containers
  tekton.dev/tags: containers
  artifacthub.io/maintainers: |
      - name: OpenShift Pipeline task maintainers
        email: pipelines-extcomm@redhat.com
  artifacthub.io/provider: Red Hat
  artifacthub.io/recommendations: |
      - url: https://tekton.dev/
  artifacthub.io/category: integration-delivery

