---
# task steps container images
images:
  bash: registry.access.redhat.com/ubi8-minimal:8.9
  skopeo: registry.access.redhat.com/ubi8/skopeo:8.9
  buildah: registry.access.redhat.com/ubi8/buildah:8.9
  s2i: registry.access.redhat.com/source-to-image/source-to-image-rhel8:v1.3.9-6
  
# source-to-image builder images, each language represents a distinct ecosystem the builder supports,
# sometimes it includes a specific version
s2iBuilders:
  python: registry.access.redhat.com/ubi8/python-39:latest
  ruby: registry.access.redhat.com/ubi9/ruby-31:1-102
  perl: registry.access.redhat.com/ubi9/perl-532:1-145
  go: registry.access.redhat.com/ubi8/go-toolset:1.20.12-5.1713833129
  nodejs: registry.access.redhat.com/ubi8/nodejs-18:latest
  php: registry.access.redhat.com/ubi9/php-81:1-54
  dotnet: registry.access.redhat.com/ubi8/dotnet-60:6.0-48
  java: registry.access.redhat.com/ubi8/openjdk-11:latest

annotations:
  tekton.dev/pipelines.minVersion: "0.41.0"
  tekton.dev/categories: containers
  tekton.dev/tags: containers
  artifacthub.io/maintainers: |
      - name: OpenShift Pipeline task maintainers
        email: pipelines-extcomm@redhat.com
  artifacthub.io/provider: Red Hat
  artifacthub.io/recommendations: |
      - url: https://tekton.dev/
  artifacthub.io/category: integration-delivery

