---
# task steps container images
images:
  bash: registry.access.redhat.com/ubi9-minimal:9.4
  skopeo: registry.access.redhat.com/ubi9/skopeo:9.4
  buildah: registry.access.redhat.com/ubi9/buildah:9.4
  s2i: registry.access.redhat.com/source-to-image/source-to-image-rhel8:v1.3.9-6
  
# source-to-image builder images, each language represents a distinct ecosystem the builder supports,
# sometimes it includes a specific version
s2iBuilders:
  python: registry.access.redhat.com/ubi9/python-39:latest
  ruby: registry.access.redhat.com/ubi9/ruby-31:1-102
  perl: registry.access.redhat.com/ubi9/perl-532:1-145
  go: registry.access.redhat.com/ubi9/go-toolset:latest
  nodejs: registry.access.redhat.com/ubi9/nodejs-18:latest
  php: registry.access.redhat.com/ubi9/php-81:1-54
  dotnet: registry.access.redhat.com/ubi8/dotnet-60:6.0-48 # No ubi9 or rhel9 for dotnet
  java: registry.access.redhat.com/ubi9/openjdk-11:latest

annotations:
  tekton.dev/pipelines.minVersion: "0.41.0"
  tekton.dev/categories: containers
  tekton.dev/tags: containers
  artifacthub.io/maintainers: |
      - name: OpenShift Pipeline task maintainers
        email: pipelines-extcomm@redhat.com
  artifacthub.io/provider: Red Hat
  artifacthub.io/recommendations: |
      - url: https://tekton.dev/
  artifacthub.io/category: integration-delivery

