---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: skopeo-copy
  labels:
    app.kubernetes.io/version: {{ .Chart.Version }}
{{- if .Values.annotations }}
  annotations:
  {{- .Values.annotations | toYaml | nindent 4 }}
{{- end }}
spec:
  description: |
    Uses `skopeo copy` to replicate the `SOURCE` (param) container image into
    `DESTINATION`. After copying the source and destination images SHA256 digest
    is stored as results.

  params:
    - name: SOURCE
      type: string
      description: |
        Fully qualified source container image name, including tag, to be copied
        into `DESTINATION` param.
    - name: DESTINATION
      type: string
      description: |
        Fully qualified destination container image name, including tag.
    - name: TLS_VERIFY
      type: string
      default: "true"
      description: |
        Sets the TLS verification flags, `true` is recommended.
    - name: VERBOSE
      type: string
      default: "false"
      description: |
        Shows a more verbose (debug) output.

  results:
    - name: SOURCE_DIGEST
      type: string
      description: |
        Source image SHA256 digest.
    - name: DESTINATION_DIGEST
      type: string
      description: |
        Destination image SHA256 digest.

  volumes:
    - name: scripts-dir
      emptyDir: {}

  stepTemplate:
    env:
{{- $variables := list
      "params.SOURCE"
      "params.DESTINATION"
      "params.TLS_VERIFY"
      "params.VERBOSE"
      "results.SOURCE_DIGEST.path"
      "results.DESTINATION_DIGEST.path"
}}
{{- include "environment" ( list $variables ) | nindent 6 }}

  steps:
{{- include "load_scripts" ( list . "skopeo-" ) | nindent 4 }}

    - name: skopeo-copy
      image: {{ .Values.images.skopeo }}
      command:
        - /scripts/skopeo-copy.sh
      volumeMounts:
        - name: scripts-dir
          mountPath: /scripts

    - name: skopeo-results
      image: {{ .Values.images.skopeo }}
      command:
        - /scripts/skopeo-results.sh
      volumeMounts:
        - name: scripts-dir
          mountPath: /scripts
