apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: s2i-go-tr
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.11.3"
    tekton.dev/tags: s2i, go, workspace
    tekton.dev/displayName: "s2i go"
spec:
  description: >-
    s2i-go task clones a Git repository and builds and
    pushes a container image using S2I and a Go builder image.

  results:
    - name: IMAGE_DIGEST
      description: Digest of the image just built.
  params:
    - name: VERSION
      description: The tag of go imagestream for go version
      default: '1.14.7-ubi8'
      type: string
    - name: PATH_CONTEXT
      description: The location of the path to run s2i from.
      default: .
      type: string
    - name: TLSVERIFY
      description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
      default: "true"
      type: string
    - name: IMAGE
      description: Location of the repo where image has to be pushed
      type: string
    - name: VERBOSE
      type: string
      default: "false"
      description: |
        Shows a more verbose (debug) output.
  workspaces:
    - name: source
      mountPath: /workspace/source
  steps:
    - name: generate
      image: quay.io/openshift-pipeline/s2i:latest
      workingDir: $(workspaces.source.path)
      command: ['s2i', 'build', '$(params.PATH_CONTEXT)','registry.redhat.io/rhel8/go-toolset:1.19.9-2', '--as-dockerfile', '/gen-source/Dockerfile.gen']
      env:
        - name: HOME
          value: /tekton/home
        - name: GO111MODULE
          value: "auto"
      volumeMounts:
        - name: gen-source
          mountPath: /gen-source
    - name: check-dockerfile
      image: busybox
      workingDir: /gen-source
      command: ['sh', '-c', 'if [ -f "/gen-source/Dockerfile.gen" ]; then echo "Dockerfile generated successfully : "; cat "Dockerfile.gen"; else echo "Failed to generate Dockerfile"; exit 1; fi']
      volumeMounts:
        - name: gen-source
          mountPath: /gen-source
    - name: build
      image: quay.io/buildah/stable:latest
      workingDir: /gen-source
      command: ['buildah', 'bud', '--storage-driver=vfs', '--tls-verify=$(params.TLSVERIFY)', '--layers', '-f', '/gen-source/Dockerfile.gen', '-t', '$(params.IMAGE)', '.']
      env:
        - name: GO111MODULE
          value: "auto"
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
        - name: gen-source
          mountPath: /gen-source
    - name: push
      workingDir: $(workspaces.source.path)
      image: quay.io/buildah/stable:latest
      command: ['buildah', 'push', '--storage-driver=vfs', '--tls-verify=$(params.TLSVERIFY)', '--digestfile=/gen-source/image-digest', '$(params.IMAGE)', 'docker://$(params.IMAGE)']
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
        - name: gen-source
          mountPath: /gen-source
    - name: digest-to-results
      image: quay.io/buildah/stable:latest
      script: cat /gen-source/image-digest | tee /tekton/results/IMAGE_DIGEST
  volumes:
    - name: varlibcontainers
      emptyDir: {}
    - name: gen-source
      emptyDir: {}